"""Added new columns to User model

Revision ID: 498cddebf24e
Revises: 
Create Date: 2025-06-05 17:45:19.801270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498cddebf24e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gitrank_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repos_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('forks', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('commits', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pulls', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('issues', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('languages', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gitrank_users', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('languages')
        batch_op.drop_column('issues')
        batch_op.drop_column('pulls')
        batch_op.drop_column('commits')
        batch_op.drop_column('forks')
        batch_op.drop_column('stars')
        batch_op.drop_column('repos_count')

    # ### end Alembic commands ###
