"""Changed score column to Integer

Revision ID: efb87ba8f227
Revises: b3c48076b907
Create Date: 2025-06-07 16:32:48.515894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb87ba8f227'
down_revision = 'b3c48076b907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gitrank_users', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gitrank_users', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
